name: biomics_agent
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - altair==6.0.0
      - anndata==0.11.4
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - array-api-compat==1.12.0
      - asttokens==3.0.1
      - async-timeout==4.0.3
      - attrs==25.4.0
      - bidict==0.23.1
      - blinker==1.9.0
      - brotli==1.2.0
      - cachetools==6.2.4
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - codeboxapi==0.2.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - decorator==5.2.1
      - distro==1.9.0
      - docutils==0.22.4
      - dotenv==0.9.9
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - faiss-cpu==1.12.0
      - fastapi==0.125.0
      - ffmpy==1.0.0
      - filelock==3.20.1
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==6.1.0
      - gradio-client==2.0.1
      - greenlet==3.3.0
      - groovy==0.1.2
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==1.2.3
      - idna==3.11
      - ifaddr==0.2.0
      - ipython==8.37.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - langchain==0.3.26
      - langchain-community==0.3.27
      - langchain-core==1.2.1
      - langchain-openai==1.1.3
      - langchain-text-splitters==0.3.11
      - langgraph==1.0.5
      - langgraph-checkpoint==2.1.2
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.3.0
      - langsmith==0.4.59
      - legacy-api-wrap==1.5
      - llvmlite==0.46.0
      - markdown-it-py==4.0.0
      - markdown2==2.5.4
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - narwhals==2.14.0
      - natsort==8.4.0
      - networkx==3.4.2
      - nicegui==3.4.1
      - numba==0.63.1
      - numpy==2.2.6
      - openai==2.12.0
      - orjson==3.11.5
      - ormsgpack==1.12.1
      - packaging==24.2
      - pandas==2.3.3
      - parso==0.8.5
      - patsy==1.0.2
      - pexpect==4.9.0
      - pillow==12.0.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydeck==0.9.1
      - pydub==0.25.1
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-engineio==4.12.3
      - python-multipart==0.0.21
      - python-socketio==5.15.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - rapidfuzz==3.14.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - safehttpx==0.1.7
      - scanpy==1.11.3
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - session-info2==0.2.3
      - shellingham==1.5.4
      - simple-websocket==1.1.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.45
      - stack-data==0.6.3
      - starlette==0.50.0
      - statsmodels==0.14.6
      - streamlit==1.52.2
      - streamlit-float==0.4.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - toml==0.10.2
      - tomlkit==0.13.3
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - umap-learn==0.5.9.post2
      - urllib3==2.6.2
      - uuid-utils==0.12.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - websocket-client==1.9.0
      - websockets==15.0.1
      - wsproto==1.3.2
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /home/liyuntian/anaconda3/envs/biomics_agent
